version: "3.4"
services:
  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - 8082:8082
    depends_on:
      - test-service
    links:
      - test-service
  mongo:
    build:
      context: ./Mongo
      args:
        - MONGO_IMAGE
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  test-service:
    build:
      context: ./InvestmentReporting.TestService
      args:
        - DOTNET_IMAGE_SUFFIX
    container_name: test-service
    ports:
      - 8083:8083