name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 2.1 (workaround)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Run compile task
      run: ./build.sh --target Compile
